### ISSUE TITLE
when adding an MPA, the form disappears with a brief message that it has been submitted successfully, but when editing an MPA that was denied, the form remains with a brief message at the bottom showing successful submission

### ISSUE THREAD

**Issue by weissna** [greenjm/MeteorExpenseReportSystem#56]
should be consistent

**Comment by astronauticalAuthor** [comment]
The reason it's not consistent is because the forms have different purposes--for edit forms, the message is shown at the bottom and disappears after a couple seconds so that another edit can happen, and for forms that add things (like submitting an MPA), the form disappears so that the same MPA can't be submitted twice. In that case the spinner is bigger and in the middle to seem more important.
